In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_excel("Dados/RelSAMPClasseConsNivel.xlsx")

In [7]:
df.head()

,Ano,Mes,DescClasseConsumo,NomeAgente,FaixaTensao,ConsumoEnergiaEletricaMWh,ReceitaFornecimentoEE,NumeroUnidadesConsumidoras,ReceitaFornecimentoEEImp,TarifaMediaFornecimento,TarifaMediaFornecimentoImp,DataUltAtu
0,2009,8,"Comercial, Serviços e Outras",AME - AMAZONAS ENERGIA S.A,"A4 (2,3 a 25 kV)",41533.57,13046417.92,771.0,17218463.85,314.1174,414.5674,44404.193322
1,2009,8,"Comercial, Serviços e Outras",AME - AMAZONAS ENERGIA S.A,B3 - Demais Classes,24082.58,8100549.72,36966.0,10795170.15,336.3655,448.2564,44404.193322
2,2009,8,Consumo Próprio,AME - AMAZONAS ENERGIA S.A,"A4 (2,3 a 25 kV)",384.92,120813.23,11.0,120813.23,313.8658,313.8658,44404.193322
3,2009,8,Consumo Próprio,AME - AMAZONAS ENERGIA S.A,B3 - Demais Classes,708.64,238237.89,20.0,238237.89,336.1903,336.1903,44404.193322
4,2009,8,Iluminação Pública,AME - AMAZONAS ENERGIA S.A,B4b - Iluminação Pública - Bulbo de Lâmpada,6599.24,1143115.49,95.0,1524153.59,173.2193,230.9590,44404.193322

In [13]:
df.to_csv("Dados/SampClasse.csv", sep='|')

In [15]:
df_csv = pd.read_csv("Dados/SampClasse.csv", sep='|')

In [16]:
df_csv.head()

,Unnamed: 0,Ano,Mes,DescClasseConsumo,NomeAgente,FaixaTensao,ConsumoEnergiaEletricaMWh,ReceitaFornecimentoEE,NumeroUnidadesConsumidoras,ReceitaFornecimentoEEImp,TarifaMediaFornecimento,TarifaMediaFornecimentoImp,DataUltAtu
0,0,2009,8,"Comercial, Serviços e Outras",AME - AMAZONAS ENERGIA S.A,"A4 (2,3 a 25 kV)",41533.57,13046417.92,771.0,17218463.85,314.1174,414.5674,44404.193322
1,1,2009,8,"Comercial, Serviços e Outras",AME - AMAZONAS ENERGIA S.A,B3 - Demais Classes,24082.58,8100549.72,36966.0,10795170.15,336.3655,448.2564,44404.193322
2,2,2009,8,Consumo Próprio,AME - AMAZONAS ENERGIA S.A,"A4 (2,3 a 25 kV)",384.92,120813.23,11.0,120813.23,313.8658,313.8658,44404.193322
3,3,2009,8,Consumo Próprio,AME - AMAZONAS ENERGIA S.A,B3 - Demais Classes,708.64,238237.89,20.0,238237.89,336.1903,336.1903,44404.193322
4,4,2009,8,Iluminação Pública,AME - AMAZONAS ENERGIA S.A,B4b - Iluminação Pública - Bulbo de Lâmpada,6599.24,1143115.49,95.0,1524153.59,173.2193,230.9590,44404.193322